In [1]:
import pandas as pd
import numpy as np

In [2]:
from google.colab import files
uploaded = files.upload()

Saving BL-Flickr-Images-Book.csv to BL-Flickr-Images-Book.csv

In [3]:
import io
df = pd.read_csv(io.BytesIO(uploaded['BL-Flickr-Images-Book.csv']))

In [4]:
df.head()

,Identifier,Edition Statement,Place of Publication,Date of Publication,Publisher,Title,Author,Contributors,Corporate Author,Corporate Contributors,Former owner,Engraver,Issuance type,Flickr URL,Shelfmarks
0,206,NaN,London,1879 [1878],S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,"FORBES, Walter.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12641.b.30.
1,216,NaN,London; Virtue & Yorston,1868,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12626.cc.2.
2,218,NaN,London,1869,"Bradbury, Evans & Co.",Love the Avenger. By the author of â€œAll for Gr...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12625.dd.1.
3,472,NaN,London,1851,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.","Appleyard, Ernest Silvanus.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 10369.bbb.15.
4,480,"A new edition, revised, etc.",London,1857,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.","BROOME, John Henry.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 9007.d.28.

In [6]:
df.isnull()

,Identifier,Edition Statement,Place of Publication,Date of Publication,Publisher,Title,Author,Contributors,Corporate Author,Corporate Contributors,Former owner,Engraver,Issuance type,Flickr URL,Shelfmarks
0,False,True,False,False,False,False,False,False,True,True,True,True,False,False,False
1,False,True,False,False,False,False,False,False,True,True,True,True,False,False,False
2,False,True,False,False,False,False,False,False,True,True,True,True,False,False,False
3,False,True,False,False,False,False,False,False,True,True,True,True,False,False,False
4,False,False,False,False,False,False,False,False,True,True,True,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8282,False,True,False,False,True,False,False,False,True,True,True,True,False,False,False
8283,False,True,False,False,False,False,False,False,True,True,True,True,False,False,False
8284,False,True,False,False,False,False,False,False,True,True,True,True,False,False,False
8285,False,True,False,False,False,False,False,False,True,True,True,True,False,False,False
8286,False,True,False,False,True,False,True,False,True,True,True,True,False,False,False

In [7]:
df.isna().sum()

Identifier                   0
Edition Statement         7514
Place of Publication         0
Date of Publication        181
Publisher                 4195
Title                        0
Author                    1778
Contributors                 0
Corporate Author          8287
Corporate Contributors    8287
Former owner              8286
Engraver                  8287
Issuance type                0
Flickr URL                   0
Shelfmarks                   0
dtype: int64

In [8]:
to_drop = ['Edition Statement',
          'Corporate Author',
          'Corporate Contributors',
          'Former owner',
          'Engraver',
           'Contributors',
           'Issuance type',
           'Shelfmarks']

In [9]:
df.drop(to_drop, inplace=True, axis=1)

In [10]:
df.head()

,Identifier,Place of Publication,Date of Publication,Publisher,Title,Author,Flickr URL
0,206,London,1879 [1878],S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,http://www.flickr.com/photos/britishlibrary/ta...
1,216,London; Virtue & Yorston,1868,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...
2,218,London,1869,"Bradbury, Evans & Co.",Love the Avenger. By the author of â€œAll for Gr...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...
3,472,London,1851,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...
4,480,London,1857,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...

In [11]:
df['Identifier'].is_unique

True

In [12]:
df = df.set_index('Identifier')
df.head()

,Place of Publication,Date of Publication,Publisher,Title,Author,Flickr URL
Identifier,,,,,,
206,London,1879 [1878],S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,http://www.flickr.com/photos/britishlibrary/ta...
216,London; Virtue & Yorston,1868,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...
218,London,1869,"Bradbury, Evans & Co.",Love the Avenger. By the author of â€œAll for Gr...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...
472,London,1851,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...
480,London,1857,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...

In [13]:
#use loc[] to do key-based locating
df.loc[206]

Place of Publication                                               London
Date of Publication                                           1879 [1878]
Publisher                                                S. Tinsley & Co.
Title                                   Walter Forbes. [A novel.] By A. A
Author                                                              A. A.
Flickr URL              http://www.flickr.com/photos/britishlibrary/ta...
Name: 206, dtype: object

In [14]:
df.loc[1905:, 'Date of Publication'].head(10)

Identifier
1905           1888
1929    1839, 38-54
2836           1897
2854           1865
2956        1860-63
2957           1873
3017           1866
3131           1899
4598           1814
4884           1820
Name: Date of Publication, dtype: object

In [15]:
regex = r'^(\d{4})'

In [16]:
extr = df['Date of Publication'].str.extract(r'^(\d{4})', expand=False)
extr.head()

Identifier
206    1879
216    1868
218    1869
472    1851
480    1857
Name: Date of Publication, dtype: object

In [17]:
#Converting to float datatype
df['Date of Publication'] = pd.to_numeric(extr)
df['Date of Publication'].dtype

dtype('float64')

In [18]:
df['Date of Publication'].isnull().sum() / len(df)

0.11717147339205986

In [19]:
df['Date of Publication'].head()

Identifier
206    1879.0
216    1868.0
218    1869.0
472    1851.0
480    1857.0
Name: Date of Publication, dtype: float64

In [20]:
df['Place of Publication'].head(10)

Identifier
206                                  London
216                London; Virtue & Yorston
218                                  London
472                                  London
480                                  London
481                                  London
519                                  London
667     pp. 40. G. Bryan & Co: Oxford, 1898
874                                 London]
1143                                 London
Name: Place of Publication, dtype: object

In [21]:
pub = df['Place of Publication']
london = pub.str.contains('London')
london[:5]

Identifier
206    True
216    True
218    True
472    True
480    True
Name: Place of Publication, dtype: bool

In [22]:
oxford = pub.str.contains('Oxford')
df['Place of Publication'] = np.where(london, 'London',np.where(oxford, 'Oxford', pub.str.replace('-', ' ')))
df['Place of Publication'].head()

Identifier
206    London
216    London
218    London
472    London
480    London
Name: Place of Publication, dtype: object

In [23]:
df.head(15)

,Place of Publication,Date of Publication,Publisher,Title,Author,Flickr URL
Identifier,,,,,,
206,London,1879.0,S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,http://www.flickr.com/photos/britishlibrary/ta...
216,London,1868.0,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...
218,London,1869.0,"Bradbury, Evans & Co.",Love the Avenger. By the author of â€œAll for Gr...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...
472,London,1851.0,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...
480,London,1857.0,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...
481,London,1875.0,William Macintosh,"[The World in which I live, and my place in it...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...
519,London,1872.0,The Author,Lagonells. By the author of Darmayne (F. E. A....,"A., F. E.",http://www.flickr.com/photos/britishlibrary/ta...
667,Oxford,NaN,NaN,"The Coming of Spring, and other poems. By J. A...","A., J.|A., J.",http://www.flickr.com/photos/britishlibrary/ta...
874,London,1676.0,NaN,"A Warning to the inhabitants of England, and L...",RemaÊ¿.,http://www.flickr.com/photos/britishlibrary/ta...
1143,London,1679.0,NaN,A Satyr against Vertue. (A poem: supposed to b...,"A., T.",http://www.flickr.com/photos/britishlibrary/ta...
1280,Coventry,1802.0,Printed by J. Turner,"An Account of the many and great Loans, Benefa...",NaN,http://www.flickr.com/photos/britishlibrary/ta...
1808,Christiania,1859.0,NaN,Erindringer som Bidrag til Norges Historie fra...,"AALL, Jacob.",http://www.flickr.com/photos/britishlibrary/ta...
1905,Firenze,1888.0,NaN,Gli Studi storici in terra d'Otranto ... Framm...,"AAR, Ermanno - pseud. [i.e. Luigi Giuseppe Oro...",http://www.flickr.com/photos/britishlibrary/ta...
1929,Amsterdam,1839.0,NaN,De Aardbol. Magazijn van hedendaagsche land- e...,NaN,http://www.flickr.com/photos/britishlibrary/ta...
2836,Savona,1897.0,NaN,Cronache Savonesi dal 1500 al 1570 ... Accresc...,"ABATE, Giovanni Agostino.",http://www.flickr.com/photos/britishlibrary/ta...

In [24]:
df[:5]

,Place of Publication,Date of Publication,Publisher,Title,Author,Flickr URL
Identifier,,,,,,
206,London,1879.0,S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,http://www.flickr.com/photos/britishlibrary/ta...
216,London,1868.0,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...
218,London,1869.0,"Bradbury, Evans & Co.",Love the Avenger. By the author of â€œAll for Gr...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...
472,London,1851.0,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...
480,London,1857.0,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...

In [34]:
towns_df = pd.DataFrame(df, columns=['Title'])
towns_df.head()

                                                        Title
Identifier
206                         Walter Forbes. [A novel.] By A. A
216         All for Greed. [A novel. The dedication signed...
218         Love the Avenger. By the author of â€œAll for Gr...
472         Welsh Sketches, chiefly ecclesiastical, to the...
480         [The World in which I live, and my place in it...

In [32]:
def get_title(item):
    if ' (' in item:
        return item[:item.find(' (')]
    elif '[' in item:
        return item[:item.find('[')]
    else:
        return item

In [35]:
towns_df = towns_df.applymap(get_title)
towns_df.head(15)

                                                        Title
Identifier
206                                           Walter Forbes.
216                                           All for Greed.
218         Love the Avenger. By the author of â€œAll for Gr...
472         Welsh Sketches, chiefly ecclesiastical, to the...
480
481
519                      Lagonells. By the author of Darmayne
667          The Coming of Spring, and other poems. By J. A.
874         A Warning to the inhabitants of England, and L...
1143                                  A Satyr against Vertue.
1280        An Account of the many and great Loans, Benefa...
1808        Erindringer som Bidrag til Norges Historie fra...
1905        Gli Studi storici in terra d'Otranto ... Framm...
1929        De Aardbol. Magazijn van hedendaagsche land- e...
2836        Cronache Savonesi dal 1500 al 1570 ... Accresc...

In [36]:
def get_title(item):
    if 'By' in item:
        return item[:item.find('By')]
    else:
        return item

In [37]:
towns_df = towns_df.applymap(get_title)
towns_df.head(15)

                                                        Title
Identifier
206                                           Walter Forbes.
216                                           All for Greed.
218                                        Love the Avenger.
472         Welsh Sketches, chiefly ecclesiastical, to the...
480
481
519                                               Lagonells.
667                   The Coming of Spring, and other poems.
874         A Warning to the inhabitants of England, and L...
1143                                  A Satyr against Vertue.
1280        An Account of the many and great Loans, Benefa...
1808        Erindringer som Bidrag til Norges Historie fra...
1905        Gli Studi storici in terra d'Otranto ... Framm...
1929        De Aardbol. Magazijn van hedendaagsche land- e...
2836        Cronache Savonesi dal 1500 al 1570 ... Accresc...

In [30]:
towns_df.head(15)

                                                        Title
Identifier
206                                           Walter Forbes.
216                                           All for Greed.
218                                        Love the Avenger.
472         Welsh Sketches, chiefly ecclesiastical, to the...
480
481
519                                               Lagonells.
667                   The Coming of Spring, and other poems.
874         A Warning to the inhabitants of England, and L...
1143                                  A Satyr against Vertue.
1280        An Account of the many and great Loans, Benefa...
1808        Erindringer som Bidrag til Norges Historie fra...
1905        Gli Studi storici in terra d'Otranto ... Framm...
1929        De Aardbol. Magazijn van hedendaagsche land- e...
2836        Cronache Savonesi dal 1500 al 1570 ... Accresc...